In [1]:
import pandas as pd
import numpy as np

In [2]:
# reading in niaaa csv data
niaaa_path = "../resources/niaaa_data_normalized.csv"
niaaa_df = pd.read_csv(niaaa_path)
niaaa_df

,Year (4-digit calendar year),"Geographic ID code (FIPS code, see specification below)",Type of beverage (see specification below),Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
0,1970,1,1,3863000,1738350,2499000,6956,9,2020000,8606,9,.,.,.,Alabama,Spirits,unknown
1,1970,1,2,1412000,225920,2499000,904,9,2020000,1118,9,.,.,.,Alabama,Wine,unknown
2,1970,1,3,33098000,1489410,2499000,5960,10,2020000,7373,10,.,.,.,Alabama,Beer,unknown
3,1970,1,4,.,3453680,2499000,13820,10,2020000,17097,10,.,.,.,Alabama,All beverages,unknown
4,1970,2,1,945000,425250,205000,20744,1,165000,25773,1,.,.,.,Alaska,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10971,2018,94,4,.,160326587,64146752,24994,.,57158011,28050,.,.,.,157741755,West Region,All beverages,unknown
10972,2018,99,1,570983458,234674202,270449061,8677,.,240910947,9741,.,.,384,219257648,United States,Spirits,unknown
10973,2018,99,2,913944969,117898901,270449061,4359,.,240910947,4894,.,.,117,106931561,United States,Wine,unknown
10974,2018,99,3,6318315520,284324198,270449061,10513,.,240910947,11802,.,.,48,303279145,United States,Beer,unknown
10975,2018,99,4,.,636897302,270449061,23550,.,240910947,26437,.,.,.,629468354,United States,All beverages,unknown

In [3]:
# renaming some columns for ease
niaaa_df_col = niaaa_df.rename(columns={"Year (4-digit calendar year)" : "Year",
                                       "Geographic ID code (FIPS code, see specification below)" : "Geo ID Code",
                                       "Type of beverage (see specification below)" : "Beverage Type Code"},
                                       )
niaaa_df_col

,Year,Geo ID Code,Beverage Type Code,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
0,1970,1,1,3863000,1738350,2499000,6956,9,2020000,8606,9,.,.,.,Alabama,Spirits,unknown
1,1970,1,2,1412000,225920,2499000,904,9,2020000,1118,9,.,.,.,Alabama,Wine,unknown
2,1970,1,3,33098000,1489410,2499000,5960,10,2020000,7373,10,.,.,.,Alabama,Beer,unknown
3,1970,1,4,.,3453680,2499000,13820,10,2020000,17097,10,.,.,.,Alabama,All beverages,unknown
4,1970,2,1,945000,425250,205000,20744,1,165000,25773,1,.,.,.,Alaska,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10971,2018,94,4,.,160326587,64146752,24994,.,57158011,28050,.,.,.,157741755,West Region,All beverages,unknown
10972,2018,99,1,570983458,234674202,270449061,8677,.,240910947,9741,.,.,384,219257648,United States,Spirits,unknown
10973,2018,99,2,913944969,117898901,270449061,4359,.,240910947,4894,.,.,117,106931561,United States,Wine,unknown
10974,2018,99,3,6318315520,284324198,270449061,10513,.,240910947,11802,.,.,48,303279145,United States,Beer,unknown
10975,2018,99,4,.,636897302,270449061,23550,.,240910947,26437,.,.,.,629468354,United States,All beverages,unknown

In [4]:
niaaa_df_col.dtypes

Year                                                   int64
Geo ID Code                                            int64
Beverage Type Code                                     int64
Gallons of beverage                                   object
Gallons of ethanol (absolute alcohol)                  int64
Population (age 14 and older)                          int64
Gallons of ethanol per capita age 14 and older         int64
Decile for per capita consumption age 14 and older    object
Population (age 21 and older)                          int64
Gallons of ethanol per capita age 21 and older         int64
Decile for per capita consumption age 21 and older    object
Type of data source                                   object
Time-varying alcohol by volume (ABV)                  object
Gallons of ethanol derived from time-varying ABV      object
State_Region                                          object
Type of Beverage                                      object
Source                                                object
dtype: object

In [5]:
# normalizing object types to float
gal_of_bev_num = pd.to_numeric(niaaa_df_col["Gallons of beverage"], errors='coerce')

In [6]:
# adding column back into the df
niaaa_df_col["Gallons of beverage"] = gal_of_bev_num

# fill na with zero
niaaa_df_col_drop = niaaa_df_col.fillna(0)
niaaa_df_col_drop

,Year,Geo ID Code,Beverage Type Code,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
0,1970,1,1,3.863000e+06,1738350,2499000,6956,9,2020000,8606,9,.,.,.,Alabama,Spirits,unknown
1,1970,1,2,1.412000e+06,225920,2499000,904,9,2020000,1118,9,.,.,.,Alabama,Wine,unknown
2,1970,1,3,3.309800e+07,1489410,2499000,5960,10,2020000,7373,10,.,.,.,Alabama,Beer,unknown
3,1970,1,4,0.000000e+00,3453680,2499000,13820,10,2020000,17097,10,.,.,.,Alabama,All beverages,unknown
4,1970,2,1,9.450000e+05,425250,205000,20744,1,165000,25773,1,.,.,.,Alaska,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10971,2018,94,4,0.000000e+00,160326587,64146752,24994,.,57158011,28050,.,.,.,157741755,West Region,All beverages,unknown
10972,2018,99,1,5.709835e+08,234674202,270449061,8677,.,240910947,9741,.,.,384,219257648,United States,Spirits,unknown
10973,2018,99,2,9.139450e+08,117898901,270449061,4359,.,240910947,4894,.,.,117,106931561,United States,Wine,unknown
10974,2018,99,3,6.318316e+09,284324198,270449061,10513,.,240910947,11802,.,.,48,303279145,United States,Beer,unknown
10975,2018,99,4,0.000000e+00,636897302,270449061,23550,.,240910947,26437,.,.,.,629468354,United States,All beverages,unknown

In [7]:
# normalizing columns by the millions
niaaa_df_col_drop["Gallons of beverage"] = niaaa_df_col_drop["Gallons of beverage"] / 1000000
niaaa_df_col_drop["Gallons of ethanol (absolute alcohol)"] = niaaa_df_col_drop["Gallons of ethanol (absolute alcohol)"] / 1000000
niaaa_df_col_drop["Population (age 14 and older)"] = niaaa_df_col_drop["Population (age 14 and older)"] / 1000000
niaaa_df_col_drop["Population (age 21 and older)"] = niaaa_df_col_drop["Population (age 21 and older)"] / 1000000
niaaa_df_col_drop

,Year,Geo ID Code,Beverage Type Code,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
0,1970,1,1,3.863000,1.738350,2.499000,6956,9,2.020000,8606,9,.,.,.,Alabama,Spirits,unknown
1,1970,1,2,1.412000,0.225920,2.499000,904,9,2.020000,1118,9,.,.,.,Alabama,Wine,unknown
2,1970,1,3,33.098000,1.489410,2.499000,5960,10,2.020000,7373,10,.,.,.,Alabama,Beer,unknown
3,1970,1,4,0.000000,3.453680,2.499000,13820,10,2.020000,17097,10,.,.,.,Alabama,All beverages,unknown
4,1970,2,1,0.945000,0.425250,0.205000,20744,1,0.165000,25773,1,.,.,.,Alaska,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10971,2018,94,4,0.000000,160.326587,64.146752,24994,.,57.158011,28050,.,.,.,157741755,West Region,All beverages,unknown
10972,2018,99,1,570.983458,234.674202,270.449061,8677,.,240.910947,9741,.,.,384,219257648,United States,Spirits,unknown
10973,2018,99,2,913.944969,117.898901,270.449061,4359,.,240.910947,4894,.,.,117,106931561,United States,Wine,unknown
10974,2018,99,3,6318.315520,284.324198,270.449061,10513,.,240.910947,11802,.,.,48,303279145,United States,Beer,unknown
10975,2018,99,4,0.000000,636.897302,270.449061,23550,.,240.910947,26437,.,.,.,629468354,United States,All beverages,unknown

In [8]:
# creating df for us as a whole
us_df = niaaa_df_col_drop.loc[niaaa_df_col_drop["State_Region"] == "United States"]
us_df

,Year,Geo ID Code,Beverage Type Code,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
220,1970,99,1,369.870000,166.441500,149.396000,11141,.,122.722000,13562,.,.,.,.,United States,Spirits,unknown
221,1970,99,2,255.801000,40.928160,149.396000,2740,.,122.722000,3335,.,.,.,.,United States,Wine,unknown
222,1970,99,3,3769.612000,169.632540,149.396000,11355,.,122.722000,13823,.,.,.,.,United States,Beer,unknown
223,1970,99,4,0.000000,377.002200,149.396000,25235,.,122.722000,30720,.,.,.,.,United States,All beverages,unknown
444,1971,99,1,382.117000,171.952650,153.347060,11213,.,125.687741,13681,.,.,.,.,United States,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10751,2017,99,4,0.000000,629.644756,268.308621,23467,.,238.814105,26365,.,.,.,623248963,United States,All beverages,unknown
10972,2018,99,1,570.983458,234.674202,270.449061,8677,.,240.910947,9741,.,.,384,219257648,United States,Spirits,unknown
10973,2018,99,2,913.944969,117.898901,270.449061,4359,.,240.910947,4894,.,.,117,106931561,United States,Wine,unknown
10974,2018,99,3,6318.315520,284.324198,270.449061,10513,.,240.910947,11802,.,.,48,303279145,United States,Beer,unknown
10975,2018,99,4,0.000000,636.897302,270.449061,23550,.,240.910947,26437,.,.,.,629468354,United States,All beverages,unknown

In [9]:
# grouping by year looking at US
year_group_us = us_df.groupby("Year")
year_group_us

In [10]:
# creating summary stats by year

# Gallons of beverage *gob*, Gallons of ethanol (absolute alcohol) *goe*, Population (age 14 and older) *pop_14*,
# Gallons of ethanol per capita age 14 and older *goe_pcap_14*, 
# Population (age 21 and older) *pop_21*, Gallons of ethanol per capita age 21 and older *goe_pcap_21*

year_gob_sum = year_group_us["Gallons of beverage"].sum()
year_goe_sum = year_group_us["Gallons of ethanol (absolute alcohol)"].sum()
year_pop_14_sum = year_group_us["Population (age 14 and older)"].sum() / 4
year_goe_pcap_14_sum = year_group_us["Gallons of ethanol per capita age 14 and older"].sum()
year_pop_21_sum = year_group_us["Population (age 21 and older)"].sum() / 4
year_goe_pcap_21_sum = year_group_us["Gallons of ethanol per capita age 21 and older"].sum()

In [11]:
# group by year df
us_gob_year_df = pd.DataFrame(year_gob_sum)
us_geo_year_df = pd.DataFrame(year_goe_sum)
us_pop_14_year_df = pd.DataFrame(year_pop_14_sum)
us_goe_pcap_14_year_df = pd.DataFrame(year_goe_pcap_14_sum)
us_pop_21_year_df = pd.DataFrame(year_pop_21_sum)
us_goe_pcap_21_year_df = pd.DataFrame(year_goe_pcap_21_sum)

print(len(us_gob_year_df))
print(len(us_geo_year_df))
print(len(us_pop_14_year_df))
print(len(us_goe_pcap_14_year_df))
print(len(us_goe_pcap_21_year_df))

49
49
49
49
49

In [12]:
# merge
merge_us_1 = pd.merge(us_gob_year_df,us_geo_year_df,left_index=True, right_index=True)
merge_us_2 = pd.merge(merge_us_1, us_pop_14_year_df,left_index=True, right_index=True)
merge_us_3 = pd.merge(merge_us_2, us_goe_pcap_14_year_df,left_index=True, right_index=True)
merge_us_4 = pd.merge(merge_us_3, us_pop_21_year_df,left_index=True, right_index=True)
us_year_df = pd.merge(merge_us_4, us_goe_pcap_21_year_df,left_index=True, right_index=True)
us_year_df

,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older
Year,,,,,,
1970,4395.283000,754.004400,149.396000,50471,122.722000,61440
1971,4597.432000,791.301780,153.347060,51602,125.687741,62958
1972,4756.230000,796.192950,156.503574,50874,128.187640,62112
1973,4985.675000,829.192840,159.460299,52001,130.623102,63480
1974,5226.544000,859.340840,162.390186,52918,133.110083,64559
1975,5383.539000,882.248210,165.424923,53332,135.748050,64992
1976,5479.721000,895.473130,168.429779,53166,138.514051,64648
1977,5670.802000,892.641420,171.341543,52098,141.335304,63158
1978,5906.943000,927.858138,174.266557,53244,144.339546,64284
1979,6162.230000,955.496136,177.072927,53960,147.397890,64824
1980,6400.897000,987.050658,179.684333,54932,150.451789,65606
1981,6564.270000,1004.856072,181.862066,55254,153.211633,65586
1982,6599.724000,1000.486644,183.909038,54401,155.988975,64138
1983,6623.854000,1001.000448,185.965957,53828,158.599232,63116
1984,6600.757055,998.536004,188.067683,53094,161.112182,61978
1985,6616.537809,997.626996,190.188994,52454,163.520489,61010
1986,6729.989719,992.977650,192.091826,51693,165.844428,59875
1987,6728.630503,986.494494,193.734532,50921,167.876217,58764
1988,6713.237635,971.772702,195.275084,49764,169.752969,57246
1989,6655.780469,957.646144,196.898357,48636,171.567356,55818
1990,6806.893782,972.652272,198.735772,48942,173.651025,56012
1991,6576.525548,923.976462,201.163781,45932,176.393468,52382
1992,6658.435000,936.156378,203.787619,45937,179.259858,52224
1993,6597.522015,919.585884,206.429677,44547,181.744143,50597
1994,6577.871372,912.335510,209.133071,43624,183.908685,49608
1995,6625.203466,912.965446,211.828626,43100,186.002233,49083
1996,6700.494296,927.647099,214.612873,43224,188.173130,49298
1997,6755.676281,934.699592,217.500826,42974,190.396559,49092
1998,6844.716502,945.525978,220.254922,42928,192.726452,49061
1999,6988.787276,967.859458,223.099823,43383,195.074714,49614
2000,7100.958395,989.245766,225.930423,43786,197.486329,50092
2001,7161.284882,996.444731,228.578068,43594,199.905689,49846
2002,7268.110503,1017.767399,231.194672,44022,202.292897,50312
2003,7300.928360,1038.213841,233.701167,44424,204.525240,50763
2004,7401.159372,1058.539136,236.561755,44747,206.919173,51158
2005,7443.178425,1078.350138,239.350769,45053,209.270142,51529
2006,7568.890860,1104.957740,242.171653,45628,211.807399,52168
2007,7733.719414,1132.213225,244.809096,46248,214.239372,52848
2008,7768.285052,1143.609844,247.384676,46227,216.672714,52781
2009,7696.839314,1145.583170,249.869828,45847,219.107510,52284
2010,7596.599890,1142.719100,252.270877,45298,221.576200,51572
2011,7636.761675,1168.163350,254.542312,45892,224.154045,52114
2012,7807.755298,1202.616896,256.895820,46814,226.844072,53015
2013,7788.052325,1208.709073,259.137618,46644,229.358004,52700
2014,7753.510111,1216.071952,261.564480,46492,231.866874,52446
2015,7796.165364,1228.190026,263.925279,46536,234.309833,52418
2016,7853.689039,1253.009828,266.191088,47072,236.679399,52941
2017,7806.238501,1259.289512,268.308621,46934,238.814105,52730
2018,7803.243947,1273.794603,270.449061,47099,240.910947,52874

In [13]:
# output data on stats by year
us_year_path = "output/niaaa_us_yearly_consumption_stats_clean.csv"
us_year_df.to_csv(us_year_path,index=True)

In [14]:
# Adding t/f column to look at just the states and not the summary values
states_list = [ 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 
               'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 
               'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 
               'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 
               'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 
               'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 
               'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

states_df = niaaa_df_col_drop.loc[niaaa_df_col_drop["State_Region"].isin(states_list)]
states_df

,Year,Geo ID Code,Beverage Type Code,Gallons of beverage,Gallons of ethanol (absolute alcohol),Population (age 14 and older),Gallons of ethanol per capita age 14 and older,Decile for per capita consumption age 14 and older,Population (age 21 and older),Gallons of ethanol per capita age 21 and older,Decile for per capita consumption age 21 and older,Type of data source,Time-varying alcohol by volume (ABV),Gallons of ethanol derived from time-varying ABV,State_Region,Type of Beverage,Source
0,1970,1,1,3.863000,1.738350,2.499000,6956,9,2.020000,8606,9,.,.,.,Alabama,Spirits,unknown
1,1970,1,2,1.412000,0.225920,2.499000,904,9,2.020000,1118,9,.,.,.,Alabama,Wine,unknown
2,1970,1,3,33.098000,1.489410,2.499000,5960,10,2.020000,7373,10,.,.,.,Alabama,Beer,unknown
3,1970,1,4,0.000000,3.453680,2.499000,13820,10,2.020000,17097,10,.,.,.,Alabama,All beverages,unknown
4,1970,2,1,0.945000,0.425250,0.205000,20744,1,0.165000,25773,1,.,.,.,Alaska,Spirits,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10951,2018,55,4,0.000000,14.177810,4.834403,29327,2,4.302174,32955,2,.,.,14065287,Wisconsin,All beverages,unknown
10952,2018,56,1,1.425973,0.586075,0.472325,12408,2,0.421045,13920,2,6,372,530462,Wyoming,Spirits,NABCA annual sales volume data
10953,2018,56,2,1.161350,0.149814,0.472325,3172,7,0.421045,3558,7,6,117,135878,Wyoming,Wine,NABCA annual sales volume data
10954,2018,56,3,12.782675,0.575220,0.472325,12178,3,0.421045,13662,4,1,48,613568,Wyoming,Beer,State monthly sales volume data
10955,2018,56,4,0.000000,1.311110,0.472325,27759,3,0.421045,31139,3,.,.,1279908,Wyoming,All beverages,unknown

In [15]:
# grouping by year looking at states
year_group_states = states_df.groupby("Year")
year_group_states

In [16]:
# creating summary stats by year

# Gallons of beverage *gob*, Gallons of ethanol (absolute alcohol) *goe*, Population (age 14 and older) *pop_14*,
# Gallons of ethanol per capita age 14 and older *goe_pcap_14*, 
# Population (age 21 and older) *pop_21*, Gallons of ethanol per capita age 21 and older *goe_pcap_21*

year_gob_sum = year_group_states["Gallons of beverage"].sum()
year_goe_sum = year_group_states["Gallons of ethanol (absolute alcohol)"].sum()
year_pop_14_sum = year_group_states["Population (age 14 and older)"].sum() / 4
year_goe_pcap_14_sum = year_group_states["Gallons of ethanol per capita age 14 and older"].sum()
year_pop_21_sum = year_group_states["Population (age 21 and older)"].sum() / 4
year_goe_pcap_21_sum = year_group_states["Gallons of ethanol per capita age 21 and older"].sum()